[package]
name = "filegram-web"
version = "0.1.0"
authors = ["Pawe≈Ç Kopel <pawel.kopel2@gmail.com>"]
edition = "2021"

[dependencies]
filegram = { path = "../filegram" }

getrandom = { version = "0.2.11", features = ["js"] }
js-sys = "0.3.66"
image = "0.24.7"
web-sys = { version = "0.3.63", features = [
    "File",
    "Blob",
    "Url",
    "ReadableStream",
] }
wasm-bindgen = "0.2.89"
yew = { version = "0.21.0", features = ["csr"] }
gloo = "0.10.0"
gloo-file = "0.3.0"
base64 = "0.21.5"

[dev-dependencies]
wasm-bindgen-test = "0.3.34"
